name: Spring CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositroy
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      
      - name: Run tests
        run: mvn test